# Generated by Django 4.2.11 on 2024-05-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
